### ISSUE TITLE
Deserialization error in GetSymbolAsync

### ISSUE THREAD

**Issue by JCloarec** [JKorf/FTX.Net#1]
Hi,
Thanks for this library! I had been working on my own implementation of the FTX API using your CryptoExchange.Net library, but will probably switch to using yours since it looks way more clean than mine!
I'll open some issues though for the errors that I encounter if you don't mind!

I get the following error when calling the GetSymbolsAsync method:
2021/08/30 16:11:40:803 | Error | FTX | [1] Deserialize JsonSerializationException: Error setting value to 'Type' on 'FTX.Net.Objects.FTXSymbol'.

**Comment by JKorf** [comment]
Hi, thanks for the report, please let me know if you find any more issues!
This should fixed in the latest version.
