### ISSUE TITLE
Trigger update

### ISSUE THREAD

**Issue by mircofx** [JKorf/FTX.Net#10]
Hi,

How can I subscribe just to the trigger order updates on the websocket? I found the enum but I can't see where is implemented a part from submitting a new trigger order.

Like socket.SubscribeToOrderUpdatesAsync()
But with trigger orders only.

Or if the same can retrieve also a property that if it's a trigger order the trigger order type is evaluated. 

Thank you

**Comment by JKorf** [comment]
Well sure, but the API doesn't offer that, so I can't provide that in the library
