### ISSUE TITLE
Missing Markets channel in Websocket subscription

### ISSUE THREAD

**Issue by mikejlachlan** [JKorf/FTX.Net#14]
It seems that the Markets channel is not available to subscribe to.

I might be missing it completely but it doesn't appear to be there:

![image](https://user-images.githubusercontent.com/87371310/142342923-17784d81-c1d4-44f8-bc05-f27c187ba4a2.png)

**Comment by mikejlachlan** [comment]
@JKorf  At risk of this going stale, just pinging you to make sure it isn't missed. Thanks!

**Comment by JKorf** [comment]
Hey, seems like I accidentally skipped this one when implementing the socket client. I'll have a look soon

**Comment by JKorf** [comment]
I've added it as `SubscribeToSymbolsUpdatesAsync` in the latest version

**Comment by mikejlachlan** [comment]
Awesome, thanks so much for that 😄
