### ISSUE TITLE
PlaceOrderAsync return 401 (sometimes)

### ISSUE THREAD

**Issue by mircofx** [JKorf/FTX.Net#16]
When posting orders for one Client, 2 or more orders receive this type of error.

`{401: Not logged in: Invalid signature }`
`{Date: Thu, 16 Dec 2021 20:39:22 GMT
Connection: keep-alive
Cache-Control: no-cache, max-age=0, private
account-id: None
Vary: Origin
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 6beab87a5833f93b-MXP
Alt-Svc: h3=":443", h3-29=":443", h3-28=":443", h3-27=":443"
}`

`{401: Not logged in: Invalid signature }`
`{Date: Thu, 16 Dec 2021 20:39:27 GMT
Connection: keep-alive
Cache-Control: private, max-age=0, no-cache
account-id: None
Vary: Origin
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 6beab879fb873751-MXP
Alt-Svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
}`

The Client is connected with:
`FTXClient client = new(new FTXClientOptions()
                    {
                        ApiCredentials = new ApiCredentials(fullClient.Apikey, fullClient.Apisecret),
                        SubaccountName = "Subaccount",
                        AffiliateCode = "Affiliate",
                        AutoTimestamp = true,
                        AutoTimestampRecalculationInterval = TimeSpan.FromMinutes(5)
                    }); `

I tried FromMinutes(30) and even seconds. 
I recognize it might be a timestamp drift from my time to the exchange time. How can I solve it?

**Comment by tiagosiebler** [comment]
I've also noticed this. Works fine for several hours/days, then suddenly I'll start getting `Not logged in: Invalid signature` errors repeatedly until a restart of the process. Then it resumes working fine for several days.

**Comment by JKorf** [comment]
This is related to you local time not being in sync with the server time. This can be fixed using a third party application to sync your local time more often, for instance the `SP TimeSync` program.

**Comment by tiagosiebler** [comment]
If it's server time, wouldn't the issue persist after restarting the process? It always seems to fix itself if I restart the process. As long as the process continues running with the issue, the issue never goes away.

**Comment by mircofx** [comment]
I managed to solve it using SP Timesync as JKorf suggested, setting it to refresh every 5 sec and disabling autotimestamp on the FTX client.

It's an issue with your local machine getting out of sync after a while. 

On aws it doesn't happen, the timestamps are synched.

**Comment by tiagosiebler** [comment]
> If it's server time, wouldn't the issue persist after restarting the process? It always seems to fix itself if I restart the process. As long as the process continues running with the issue, the issue never goes away.

Another worthy mention, I have multiple processes running on the same dedicated server. While one might get stuck in this "invalid signature" state, the others are completely fine. And again, as soon as I restart the stuck process it resumes working successfully. Something seems off on a process level. If it was on the OS level, others would also start throwing invalid signature errors at the same time... any ideas what might cause this?

**Comment by JKorf** [comment]
Yes, the library has an `AutoTimestamp` option, which is enabled by default. It'll try to sync the time between client and server by requesting the server time and comparing it to the local time, then adding an offset to subsequent requests. Which is why it might works at first, but when the time drifts apart it might stop working until a restart. 
The way to go with timestamping issues is having the clocks in sync instead of trying to solve the issue with software.

**Comment by JKorf** [comment]
If anyone still has issue let me know
