### ISSUE TITLE
Get fills, GetUserTradesAsync, Deserialize JsonSerializationException when processing fill "type": "expiration"

### ISSUE THREAD

**Issue by llerrowa** [JKorf/FTX.Net#18]
Calling GetUserTradesAsync (https://docs.ftx.com/#fills) fails to deserialize for expiration fills which do have a null orderId and tradeId. 
{: Deserialize JsonSerializationException: Error converting value {null} to type 'System.Int64'. Path 'result[0].orderId', line 1, position 207. [Data only available in Debug LogLevel]}

Example response from FTX  GET fills:
{
    "success": true,
    "result": [
        {
            "id": 123,
            "market": "BTT-PERP",
            "future": "BTT-PERP",
            "baseCurrency": null,
            "quoteCurrency": null,
            "type": "expiration",
            "side": "buy",
            "price": 1.234,
            "size": 123456.0,
            "orderId": null,
            "time": "2022-01-17T02:00:0.012345+00:00",
            "tradeId": null,
            "feeRate": 0.0,
            "fee": 0.0,
            "feeCurrency": "USD",
            "liquidity": "taker"
        }
    ]
}

To fix in we would need to make OrderId and TradeId nullable longs in FTXUserTrade. This would resolve the issue in both the rest and socket clients, where the issue is prevalent.

**Comment by JKorf** [comment]
I've pushed version 0.1.10 where this has been fixed

**Comment by llerrowa** [comment]
thanks for the quick fix
