### ISSUE TITLE
Missing status in FTXTriggerOrder

### ISSUE THREAD

**Issue by JCloarec** [JKorf/FTX.Net#2]
I get a deserialization error when requesting trigger order history with the GetTriggerOrdersAsync method.
2021/08/30 16:24:22:898 | Error | FTX  | [1] Deserialize JsonSerializationException: Error setting value to 'Status' on 'FTX.Net.Objects.Spot.FTXTriggerOrder'.
The current New/Open/Closed possible values for OrderStatus are correct for regular orders, but are missing some values for triggers orders. The possible status values for trigger orders are open, cancelled, and triggered as per FTX API documentation.

**Comment by JKorf** [comment]
This should fixed in the latest version.
