### ISSUE TITLE
Deserialize error in TradeApi.Account.GetDepositHistoryAsync

### ISSUE THREAD

**Issue by CitrusVento** [JKorf/FTX.Net#27]
-1 [558] Deserialize JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path 'result[0].confirmedTime', line 1, position 383. data: {\r\n  \"success\": true,\r\n  \"result\": [\r\n    {\r\n      \"id\": 19068986,\r\n    ....     \"status\": \"unconfirmed\",\r\n      \"time\": \"2022-04-15T11:13:47.444108+00:00\",\r\n      \"sentTime\": \"2022-04-15T11:13:04+00:00\",\r\n      \"confirmedTime\": null,\r\n      \"confirmations\": 11,\r\n      \"method\": \"arbitrum\"\r\n    }\r\n  ]\r\n}

For unconfirmed depositis confirmedTime is null. Type of ConfirmTime property of FTXDeposit should be 'DateTime?'

**Comment by JKorf** [comment]
Fixed in latest version
