### ISSUE TITLE
GetDepositHistoryAsync Mapping Issue

### ISSUE THREAD

**Issue by nathan-datusarator** [JKorf/FTX.Net#29]
Cannot map enum value. EnumType: FTX.Net.Enums.DepositStatus, Value: **complete**, Known values: confirmed, unconfirmed, cancelled, completed. If you think complete should added please open an issue on the Github repo.

This was marked fixed on Feb 24th, but even that had the status as complete not completed.   the Withdrawal one is mapped correctly.

**Comment by JKorf** [comment]
You're right, seems like it wasn't fixed correctly. Should be good now
