### ISSUE TITLE
GetSymbols the last could be null

### ISSUE THREAD

**Issue by chichoncoin** [JKorf/FTX.Net#3]
**Describe the bug**
Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'result[2].last'

**To Reproduce**
var symbols = await client.GetSymbolsAsync().ConfigureAwait(false);

GetSymbols the last could be null so to set decimal? instead of decimal

**Comment by JKorf** [comment]
Hi, I noticed this, its already fixed in the latest version
