### ISSUE TITLE
 When using ftx.us, FTXClient adds "FTX-SUBACCOUNT" header rather than "FTXUS-SUBACCOUNT"

### ISSUE THREAD

**Issue by jbaarsch2** [JKorf/FTX.Net#30]
**Description**
When using FtxClient to place trades on FTX.us using a sub account, the account is not parsed by the FTX.us api because the header does not match.  

**To Reproduce**
```
var options = new FTXClientOptions
            {
                ApiOptions =
                {
                    BaseAddress = FTXApiAddresses.Us.RestClientAddress
                },
                SubaccountName = settings.SubAccount,
                ApiCredentials = new ApiCredentials(settings.ApiKey, settings.ApiSecret),
                AffiliateCode = null
            };
_ftxClient = new FTXClient(options);

var orderData = await _ftxClient.TradeApi.Trading.PlaceOrderAsync(
                ftxOrder.Market,
                ftxOrder.Side,
                OrderType.Limit,
                ftxOrder.Size,
                ftxOrder.Price, 
                subaccountName: settings.SubAccount);

```

**Expected behavior**
I would expect the "FTXUS-SUBACCOUNT" http header to be added to the request. 
[Reference Documentation ](https://docs.ftx.us/#authentication)

**Actual behavior**
"FTX-SUBACCOUNT" http header is added to the request.

**Current Workaround**
Not use sub account when working with ftx.us.  Using api key for main account and placing trades in main account on ftx.us.

**Comment by JKorf** [comment]
Thanks for the report, should be fixed in the latest version
