### ISSUE TITLE
Way to identify the WS and REST connections

### ISSUE THREAD

**Issue by mircofx** [JKorf/FTX.Net#4]
Hello, 
I'm trying to connect multiple clients to the exchange. Each client should have their own ws open to get fills and update, but I need a way to distinguish them.
For example, I open 2 private ws connections A & B, and they start receiving data of the fills through the OnStatusChange or with a event triggered from price update, I want to know if the update come from socket A or socket B. 

I don't know if you think this will be useful to implement in your repository. Otherwise I'll proceed to modify yours on my local adding a item in the class to identify the ID of the WS. 

Thank for producing this repository, it's immensely useful for the project I'm currently developing.

**Comment by JKorf** [comment]
Can't you just solve this with a lamba?
````C#
await ftxSocketClient1.SubscribeToOrderUpdatesAsync(data => HandleOrderUpdate("ID1", data));
await ftxSocketClient1.SubscribeToOrderUpdatesAsync(data => HandleOrderUpdate("ID2", data));

private void HandleOrderUpdate(string client, DataEvent<FTXOrder> order)
{

}
````

**Comment by mircofx** [comment]
I've tried your solution, works very well with 2 accounts, it managed to distinguish the fills/orders correctly.
Tonight I'll try to test it with many accounts. Thanks for the solution! 
I'll close the issue tonight after testing.

**Comment by mircofx** [comment]
Tested and it's working perfectly! 
Looking forward the next releases of this repository.
