### ISSUE TITLE
Missing Endpoint "Future stats"

### ISSUE THREAD

**Issue by Amannda123** [JKorf/FTX.Net#6]
Hi, 

again thanks for your work ... 
i checked the reposititory but couldnt find that endpoint: GET /futures/{future_name}/stats

Could you add this please? i would love to get openInterest on future contracts :)

thanks

**Comment by JKorf** [comment]
Hi, turns out I missed all the /future endpoints when implementing. I've added them in the latest version

**Comment by Amannda123** [comment]
Thank you <3
